version: 2.1


orbs:
  python: circleci/python@1.5.0


jobs:
  tests:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run linting
          command: flake8

  docker-build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            export TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t "$TAG" -t web:latest .
            
  heroku-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-23 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-23 web

workflows:
  test-and-deploy:
    jobs:
      - tests
      - docker-build:
          requires:
            - tests
          filters:
            branches:
              only: master
      - heroku-deploy:
          requires:
              - tests
              - docker-build
          filters:
            branches:
              only: master