version: 2.1


orbs:
  python: circleci/python@1.5.0


jobs:
  tests:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run linting
          command: flake8

  docker-build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker build -t "$DOCKER_USERNAME"/oc_lettings:"$CIRCLE_SHA1" --platform linux/x86_64 .
            docker push "$DOCKER_USERNAME"/oc_lettings:"$CIRCLE_SHA1"
            
  heroku-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            docker pull $DOCKERHUB_USERNAME/oc-lettings:$CIRCLE_SHA1
            HEROKU_API_KEY=${HEROKU_TOKEN} docker push registry.heroku.com/oc-lettings-26/web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-26 web

workflows:
  test-and-deploy:
    jobs:
      - tests
      - docker-build:
          requires:
            - tests
          filters:
            branches:
              only: master
      - heroku-deploy:
          requires:
              - tests
              - docker-build
          filters:
            branches:
              only: master